name: CR Issue Creation to submitted tag.
on:
  issues:
    types: [opened]
permissions:
  issues: write
  contents: read
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            try {
              const issue = context.payload.issue;
              
              // Check if issue title starts with [CR]
              if (!issue.title.startsWith('[CR]')) {
                console.log('Not a CR issue, skipping...');
                return;
              }
              
              // First, add the issue to the project
              const addToProjectMutation = `
                mutation {
                  addProjectV2ItemById(input: {
                    projectId: "PVT_kwHOBJsXdM4Arizg"
                    contentId: "${issue.node_id}"
                  }) {
                    item {
                      id
                    }
                  }
                }
              `;
              
              const projectResult = await github.graphql(addToProjectMutation);
              console.log('Added issue to project');
              
              // Then set its status to 'submitted'
              const setStatusMutation = `
                mutation {
                  updateProjectV2ItemFieldValue(
                    input: {
                      projectId: "PVT_kwHOBJsXdM4Arizg"
                      itemId: "${projectResult.addProjectV2ItemById.item.id}"
                      fieldId: "PVTSSF_lAHOBJsXdM4ArizgzginKI8"
                      value: {
                        singleSelectOptionId: "cf27edac"
                      }
                    }
                  ) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;
              
              await github.graphql(setStatusMutation);
              console.log('Set status to submitted');
              
              // Add the 'submitted' label
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ['submitted']
              });
              
              console.log('Successfully set up new CR issue in project');
              
            } catch (error) {
              console.error('Error occurred:', error);
              console.error('Error message:', error.message);
              throw error;
            }
