name: Close Issue on Project Status

on:
  project_card:
    types: [converted, moved]

permissions:
  issues: write
  repository-projects: read

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            try {
              // Query to check the current status of the issue in the project
              const projectQuery = `
                query($itemId: ID!) {
                  node(id: $itemId) {
                    ... on ProjectV2Item {
                      fieldValues(first: 20) {
                        nodes {
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            name
                            field {
                              ... on ProjectV2SingleSelectField {
                                name
                              }
                            }
                          }
                        }
                      }
                      content {
                        ... on Issue {
                          number
                          repository {
                            name
                            owner {
                              login
                            }
                          }
                        }
                      }
                    }
                  }
                }
              `;
              
              const result = await github.graphql(projectQuery, {
                itemId: context.payload.project_card.node_id
              });
              
              // Check if status is "Closed"
              const statusField = result.node.fieldValues.nodes.find(
                node => node.field?.name === 'Status' && node.name === 'Closed'
              );
              
              if (statusField) {
                const issue = result.node.content;
                if (issue) {
                  // Close the issue
                  await github.rest.issues.update({
                    owner: issue.repository.owner.login,
                    repo: issue.repository.name,
                    issue_number: issue.number,
                    state: 'closed'
                  });
                  
                  console.log(`Closed issue #${issue.number}`);
                }
              }
            } catch (error) {
              console.error('Error occurred:', error);
              throw error;
            }
