name: CR Branch Status Management

on:
  create:
    branches:
      - '*'

permissions:
  issues: write
  contents: read

jobs:
  update-status:
    runs-on: ubuntu-latest
    if: contains(github.ref_name, '-cr-')
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            try {
              // Extract issue number from branch name using context
              const branchName = context.ref_name || context.payload.ref;
              const issueNumber = parseInt(branchName.match(/^(\d+)-cr-/)?.[1]);
              
              if (!issueNumber) {
                console.log('Could not extract issue number from branch name:', branchName);
                return;
              }

              // Query for the issue's project item
              const issueQuery = `
                query($owner: String!, $repo: String!, $number: Int!) {
                  repository(owner: $owner, name: $repo) {
                    issue(number: $number) {
                      projectItems(first: 1) {
                        nodes {
                          id
                        }
                      }
                    }
                  }
                }
              `;
              
              const issueResult = await github.graphql(issueQuery, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                number: issueNumber
              });
              
              const projectItem = issueResult.repository.issue.projectItems.nodes[0];
              
              if (!projectItem) {
                console.log('Issue not found in project');
                return;
              }
              
              // Update the status to Committed
              const mutation = `
                mutation {
                  updateProjectV2ItemFieldValue(
                    input: {
                      projectId: "PVT_kwHOBJsXdM4Arizg"
                      itemId: "${projectItem.id}"
                      fieldId: "PVTSSF_lAHOBJsXdM4ArizgzginKI8"
                      value: {
                        singleSelectOptionId: "30c5553b"
                      }
                    }
                  ) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `;
              
              await github.graphql(mutation);
              
              console.log('Successfully updated project item status to Committed');
              
            } catch (error) {
              console.error('Error occurred:', error);
              throw error;
            }
