name: Update Issue Status on Assignment

on:
  issues:
    types: [assigned]

jobs:
  update-issue-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check if Issue is CR
        id: check_cr
        uses: actions/github-script@v6
        with:
          script: |
            const isCR = context.payload.issue.title.startsWith('[CR]');
            return isCR;
      
      - name: Update Issue Label and Project
        if: steps.check_cr.outputs.result == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { issue, repository } = context.payload;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

            // Change label from 'submitted' to 'review'
            const labels = issue.labels.map(label => label.name);
            if (labels.includes('submitted')) {
              await octokit.rest.issues.update({
                owner: repository.owner.login,
                repo: repository.name,
                issue_number: issue.number,
                labels: labels.filter(label => label !== 'submitted').concat('review'),
              });
            }

            // Move issue to 'review' column in Project #2
            const projectNumber = 2;
            const projectColumns = await octokit.rest.projects.listColumns({
              project_id: projectNumber,
            });
            const submittedColumn = projectColumns.data.find(column => column.name === 'submitted');
            const reviewColumn = projectColumns.data.find(column => column.name === 'review');
            
            if (submittedColumn && reviewColumn) {
              const cards = await octokit.rest.projects.listCards({
                column_id: submittedColumn.id,
              });
              const card = cards.data.find(card => card.content_url && card.content_url.includes(`/issues/${issue.number}`));
              
              if (card) {
                await octokit.rest.projects.moveCard({
                  card_id: card.id,
                  position: 'top',
                  column_id: reviewColumn.id,
                });
              }
            }
          env:
            GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
