name: CR Issue Label Management

on:
  issues:
    types: [assigned]

jobs:
  update-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            
            // Check if issue title starts with [CR]
            if (!issue.title.startsWith('[CR]')) {
              console.log('Not a CR issue, skipping...');
              return;
            }
            
            // Check if issue has 'submitted' label
            const hasSubmittedLabel = issue.labels.some(label => label.name === 'submitted');
            if (!hasSubmittedLabel) {
              console.log('Issue does not have submitted label, skipping...');
              return;
            }
            
            // Remove 'submitted' label and add 'review' label
            await github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              name: 'submitted'
            });
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: ['review']
            });
            
            console.log('Successfully updated labels');
